[platformio]
default_envs = router_esp32_uart

[env]
platform = espressif32@6.10.0
framework = espidf
monitor_speed = 921600
board_build.flash_mode = dio
board_upload.flash_size = 8MB
board_build.flash_size = 8MB

[env:router_esp32_uart]
board = esp32dev
board_build.sdkconfig = sdkconfig.router_esp32_uart

[env:router_c3_uart]
board = esp32-c3-devkitm-1
board_build.sdkconfig = sdkconfig.router_c3_uart
