[platformio]
default_envs = c6_receiver, c6_transmitter

[env]
platform = espressif32@6.10.0
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 921600
board_build.flash_mode = dio
board_upload.flash_size = 4MB
board_build.flash_size = 4MB

[env:c6_receiver]
build_flags = -DWS_ROLE_TX=0
board_build.sdkconfig = sdkconfig.c6_receiver

[env:c6_transmitter]
build_flags = -DWS_ROLE_TX=1
board_build.sdkconfig = sdkconfig.c6_transmitter
