name: safehub_app
description: "SafeHub ATLAS application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  audioplayers_atlas:
    path: /opt/flutter-atlas-plugins/packages/flutter-plugin-atlas-audioplayers
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mqtt_client: 10.5.1
  http: ^1.2.2
  audioplayers: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/safehub_living_room.png
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
